 # **Jimenez, Christian Rhyss R.** 
 # **Ofamin, Christian**

# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [797]:
import numpy as np

#### 2. Print the numpy version

In [798]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [799]:
null_array = np.full(5, None)
print(null_array)

[None None None None None]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [800]:
null_array_15 = np.full(15, None)
null_array_15[6] = 1
print(null_array_15)

[None None None None None None 1 None None None None None None None None]


#### 5. Create a 4x4 matrix with values ranging from 0 to 15

In [801]:
four_by_four_mat = np.arange(16).reshape(4, 4)
print(four_by_four_mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [802]:
arr = np.array([1, 2, 4, 0, 4, 0])
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [803]:
random_array = np.random.rand(4,4,4)
print(random_array)

[[[0.61828179 0.73718734 0.56276048 0.99477525]
  [0.57588838 0.27558781 0.46871552 0.40215389]
  [0.57439076 0.61044957 0.52576065 0.65044969]
  [0.97237443 0.144008   0.84682466 0.80247333]]

 [[0.40667254 0.35835274 0.01317993 0.79897584]
  [0.81322068 0.30521241 0.18434227 0.35852095]
  [0.2514688  0.50145152 0.29242857 0.38140865]
  [0.22365207 0.16437817 0.35343759 0.27314202]]

 [[0.03586057 0.20003659 0.57242377 0.95056518]
  [0.4654564  0.6348278  0.3898903  0.29636209]
  [0.51096535 0.67142697 0.84079156 0.91487233]
  [0.58612827 0.42028125 0.71565189 0.32269872]]

 [[0.95846844 0.95603979 0.08220914 0.02230432]
  [0.98378112 0.96200425 0.80091737 0.45684199]
  [0.78450099 0.38858463 0.3841868  0.4155212 ]
  [0.79110042 0.06441317 0.90257833 0.77007275]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [804]:
minmax_array = np.random.rand(15,15) 
print("Array:\n", minmax_array)

Array:
 [[0.8831564  0.76431397 0.59943574 0.81495941 0.18327061 0.4946611
  0.38832982 0.46109275 0.78599791 0.50339631 0.3261865  0.10465866
  0.60162843 0.90868481 0.91026572]
 [0.70097615 0.35614867 0.14209062 0.76740805 0.35037265 0.50832371
  0.45097777 0.60893531 0.51580003 0.41205966 0.17338214 0.72173849
  0.97002002 0.06427514 0.34165084]
 [0.17543406 0.7206847  0.3357824  0.38277726 0.4296952  0.30405879
  0.49320261 0.65707632 0.611891   0.05560763 0.79102105 0.82132726
  0.34029439 0.3859195  0.3477638 ]
 [0.89559552 0.87305735 0.79126069 0.18453353 0.58344491 0.43748283
  0.53449691 0.52156208 0.1111579  0.68746813 0.97185275 0.80850885
  0.94415926 0.70664857 0.48520245]
 [0.08408695 0.34883202 0.75354873 0.02259171 0.13301044 0.05354459
  0.55250646 0.82999423 0.38303405 0.93511264 0.74669415 0.24071355
  0.45698481 0.96974151 0.01796322]
 [0.78302327 0.19549084 0.82287643 0.80508163 0.20839237 0.44630996
  0.92165751 0.740507   0.54448264 0.49260156 0.60647025 0.732668

In [805]:
min_val = np.min(minmax_array)
max_val = np.max(minmax_array)

print("Min Value:", min_val)
print("Max Value:", max_val)

Min Value: 0.00528338599363154
Max Value: 0.9975471094684921


#### 9. Create a random array of size 25 and find the mean value

In [806]:
random_arr_25 = np.random.random(size=(25)) 
mean_value = np.mean(random_arr_25)

print("Array:", random_arr_25)
print("\nMean Value:", mean_value)

Array: [0.5194717  0.08953693 0.29520619 0.40526484 0.4356598  0.31393488
 0.74797668 0.08308876 0.56310882 0.20678597 0.2344304  0.8076936
 0.65282744 0.9277465  0.90606566 0.64619199 0.60280459 0.43541938
 0.53964882 0.79379041 0.30700117 0.69954844 0.79839674 0.986199
 0.23429354]

Mean Value: 0.529283690537047


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [807]:
array1 = np.array([2, 4, 9])
array2 = np.array([1, 14, 6])

print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [2 4 9]
Array 2: [ 1 14  6]


10.1 What is the result of *a + b*?

In [808]:
sum = array1 + array2
print(sum)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [809]:
difference = array1 - array2
print(difference)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [810]:
product = array1 * array2
print(product)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [811]:
quotient = array1 / array2
print(quotient)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [812]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) * 10
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [813]:
element_50 = matrix[1, 1]
print(element_50)

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [814]:
row_2 = matrix[1]
print(row_2)

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [815]:
col_3 = matrix[2]
print(col_3)

[70 80 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [816]:
submat = matrix[1:3, 1:3]

print(submat)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [817]:
matrix_two = np.arange(1, 13).reshape(3,4)
print(matrix_two)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [818]:
submat_two = matrix_two[1:3, 1:3]
print(submat_two)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [819]:
row_1_every_other_element = matrix_two[0, 0::2]
print(row_1_every_other_element)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [820]:
reverse_rows = matrix_two[3::-1, 3::-1]
print(reverse_rows)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


5. Write code to extract the last two columns of the matrix.

In [821]:
last_2_col = matrix_two[0::, 2::]
print(last_2_col)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [822]:
arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

print(arr1)
print(arr2)


[11  7 33]
[44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [823]:
concat_arr = np.concatenate((arr1, arr2))
print(concat_arr)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [824]:
stack_arr = np.stack((arr1, arr2))
print(stack_arr)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [825]:
arr1_new = np.array([[1, 2], [3, 4]])

arr2_new = np.array([[5, 6], [7, 8]])

5. Write code to join them horizontally (column-wise).

In [826]:
hstack_arr = np.hstack((arr1_new, arr2_new))
print(hstack_arr)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [827]:
vstack_arr = np.vstack((arr1_new, arr2_new))
print(vstack_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [828]:
arr_1D = np.arange(10, 30, 2)
arr_2D = np.random.randint(1, 50, size=(4,4))
arr_3D = np.ones((2 ,3 ,4))

print(arr_1D)
print(arr_2D)
print(arr_3D)

[10 12 14 16 18 20 22 24 26 28]
[[37 39 26 45]
 [30 25  9  1]
 [35 10 29 29]
 [22 39 41 31]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [829]:
arr_1D_to_2D = arr_1D.reshape(2, -1)
arr_2D_last_two_rows = arr_2D[2:4, ::]

print(arr_1D_to_2D, " \n")
print(arr_2D_last_two_rows, "\n")

arr_2D_new = arr_2D.copy()

for row in range(len(arr_2D_new)):
  for col in range(len(arr_2D_new[row])):
    if arr_2D_new[row, col] % 2 == 0:
      arr_2D_new[row, col] = -1

print("Old:\n", arr_2D)
print("\nNew: \n", arr_2D_new)

[[10 12 14 16 18]
 [20 22 24 26 28]]  

[[35 10 29 29]
 [22 39 41 31]] 

Old:
 [[37 39 26 45]
 [30 25  9  1]
 [35 10 29 29]
 [22 39 41 31]]

New: 
 [[37 39 -1 45]
 [-1 25  9  1]
 [35 -1 29 29]
 [-1 39 41 31]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [830]:
print("arr_2D:\n", arr_2D)

arr_2D_mean = np.mean(arr_2D)
arr_2D_median = np.median(arr_2D)
arr_2D_std = np.std(arr_2D)
arr_2D_max = np.max(arr_2D)
arr_2D_max_idx = np.where(arr_2D == arr_2D_max)
arr_2D_sum = np.sum(arr_2D)

print("Mean: ", arr_2D_mean)
print("Median: ", arr_2D_median)
print("Standard Deviation: ", arr_2D_std)
print("Max: ", arr_2D_max, arr_2D_max_idx)
print("Sum: ",arr_2D_sum)
 


arr_2D:
 [[37 39 26 45]
 [30 25  9  1]
 [35 10 29 29]
 [22 39 41 31]]
Mean:  28.0
Median:  29.5
Standard Deviation:  12.010412149464313
Max:  45 (array([0]), array([3]))
Sum:  448


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

[[0.68729175 0.83985447 0.60057671 0.90528664 0.89601034 0.40211586
  0.07167785 0.91529183 0.63447961 0.7806296 ]
 [0.60142046 0.29276041 0.28321487 0.48712973 0.52886016 0.74234065
  0.36379993 0.57505708 0.97629359 0.17923512]
 [0.05566897 0.42136297 0.02606918 0.49921139 0.29864853 0.61978015
  0.48420891 0.33565838 0.18533866 0.58766076]
 [0.01007082 0.39908506 0.31199066 0.49058277 0.76591883 0.76243364
  0.38711422 0.77790258 0.72451445 0.58564729]
 [0.10149264 0.41108631 0.58611262 0.86704036 0.45432938 0.1127734
  0.64040266 0.25332004 0.35521537 0.51557639]
 [0.57519577 0.87427539 0.26255356 0.02020749 0.0430824  0.66205272
  0.08239304 0.10454199 0.58294326 0.71600172]
 [0.90093201 0.25985389 0.70605962 0.79406784 0.92446812 0.60007229
  0.32643092 0.83674404 0.82684124 0.41909553]
 [0.36176429 0.30342731 0.70551368 0.72932311 0.42584499 0.95605669
  0.12697277 0.1575605  0.20918778 0.38732871]
 [0.35144328 0.4052191  0.53434283 0.41237803 0.01752089 0.1634489
  0.55954053 0