# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [2]:
import numpy as np

#### 2. Print the numpy version

In [35]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [48]:
empty_array = np.empty(5)
print(empty_array)

[0.00000000e+000 1.16381525e-311 1.16381524e-311 1.16381525e-311
 0.00000000e+000]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [43]:
arr = np.array([], ndmin=(15))
arr[6] = 1
print(arr)

IndexError: index 6 is out of bounds for axis 0 with size 1

#### 5. Create a 4x4 matrix with values ranging from 0 to 15

In [49]:
matrix = np.arange(16).reshape(4, 4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [50]:
arr = np.array([1, 2, 4, 0, 4, 0])
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [51]:
random_array = np.random.random((4, 4, 4))
print(random_array)

[[[0.06476325 0.24773479 0.39218603 0.57452866]
  [0.06347279 0.99619035 0.33913849 0.17387128]
  [0.23332747 0.48184129 0.20270221 0.36410039]
  [0.93040966 0.31833339 0.93617321 0.06018977]]

 [[0.03834039 0.32853981 0.59795649 0.94182651]
  [0.14466758 0.69068956 0.93847771 0.86748759]
  [0.87723479 0.6144736  0.34678529 0.51695943]
  [0.58501086 0.95285326 0.92740544 0.73270519]]

 [[0.95459729 0.45957961 0.26736366 0.58320192]
  [0.46766158 0.93646808 0.0489208  0.36372616]
  [0.76915704 0.26418862 0.21053991 0.20633106]
  [0.4950969  0.35886901 0.69697934 0.45022586]]

 [[0.3686053  0.07194868 0.39513448 0.09887732]
  [0.81708705 0.02189425 0.68955656 0.1119504 ]
  [0.24699963 0.43791383 0.10825586 0.83850463]
  [0.32602584 0.3637095  0.89197709 0.13121722]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [52]:
array = np.random.randint(0, 100, (15, 15))  
min_val = np.min(array)
max_val = np.max(array)

print("Array:\n", array)
print("\nMin Value:", min_val)
print("Max Value:", max_val)

Array:
 [[73  5 37 51 75 58 58 54 23  4 43 80 81 69 32]
 [44 28 74 63 80 86 32 97 29 66 84 23 27 34 10]
 [76 45 55 81 93 25 38 57 20 32 13  8 70 22 98]
 [29 67 89 53  7 71 50 43 76 47 72 52 37 31 19]
 [49 18 53 36 36 78 47 61 85  9 39 80 38 37 41]
 [12 31 83 35 40 95 58 24 94 53  6 83 46 25 63]
 [57 37  3 60 98 28 39 31 98  4 30 82 48 48 78]
 [66  6  3 78 94 81 19 91 25 38  0 64 43 75 21]
 [18 74 67 70 20  3 12 49 12 11 10 43 53 35 97]
 [80 88 96 26  6 67  3 11 83 46 99 61 78 36 37]
 [ 3 49 98 89 36 53 29  0 31 31 14 60 11 68 89]
 [62 91 13 94 33 85 10 56 62 93 13 50 65 56 21]
 [14 98 73 24 79 79 45 73 14 94 57 77 34 28 57]
 [46 30 55 99 43 34 33 95 31 37 43 43 37 80 85]
 [99 52 52 81 37  5 30  6 79 53 33 59 71 84 49]]

Min Value: 0
Max Value: 99


#### 9. Create a random array of size 25 and find the mean value

In [53]:
array = np.random.randint(0, 100, 25) 
mean_value = np.mean(array)

print("Array:\n", array)
print("\nMean Value:", mean_value)

Array:
 [66 57 24 19 22 37 61 36 42 25 14 16 65 39  2 20 69 34 74 33 86 53 94 14
 67]

Mean Value: 42.76


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [54]:
array1 = np.array([2, 4, 9])
array2 = np.array([1, 14, 6])

print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [2 4 9]
Array 2: [ 1 14  6]


10.1 What is the result of *a + b*?

In [55]:
sum = array1 + array2
print(sum)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [56]:
difference = array1 - array2
print(difference)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [57]:
product = array1 * array2
print(product)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [59]:
quotient = array1 / array2
print(quotient)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [8]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [13]:
matrix[2, 2]
# print(matrix[1, 1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [15]:
matrix[1]
# print(matrix[1])

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [16]:
matrix[2]
# print(matrix[2])

[70 80 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [36]:
submat = matrix[1:3, 1:3]

# print(submat)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [13]:
matrix_two = np.array([[1, 2, 3 ,4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(matrix_two)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [25]:
submat_two = matrix_two[1:3, 1:3]
print(submat_two)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [34]:
submat_three = matrix_two[1:3:2]
print(submat_three)

[[5 6 7 8]]


4. Write code to reverse the order of rows in the matrix

5. Write code to extract the last two columns of the matrix.

##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

2. Write code to join arr1 and arr2 into a single 1D array.

3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

5. Write code to join them horizontally (column-wise).

6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.