 # **Jimenez, Christian Rhyss R.** 
 # **Ofamin, Christian**

# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [831]:
import numpy as np

#### 2. Print the numpy version

In [832]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [833]:
null_array = np.full(5, None)
print(null_array)

[None None None None None]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [834]:
null_array_15 = np.full(15, None)
null_array_15[6] = 1
print(null_array_15)

[None None None None None None 1 None None None None None None None None]


#### 5. Create a 4x4 matrix with values ranging from 0 to 15

In [835]:
four_by_four_mat = np.arange(16).reshape(4, 4)
print(four_by_four_mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [836]:
arr = np.array([1, 2, 4, 0, 4, 0])
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [837]:
random_array = np.random.rand(4,4,4)
print(random_array)

[[[0.93859317 0.38324295 0.83501036 0.75122497]
  [0.10953693 0.84382725 0.37844717 0.93364465]
  [0.17740396 0.2128509  0.7841341  0.26299513]
  [0.58005539 0.77152919 0.33783878 0.51404652]]

 [[0.00398537 0.72574227 0.82593227 0.1001476 ]
  [0.32390177 0.72562101 0.99239908 0.78840242]
  [0.75710538 0.03785142 0.78899928 0.26923292]
  [0.23526419 0.42439649 0.59721619 0.80922935]]

 [[0.09837074 0.58512076 0.60145333 0.59520058]
  [0.07886242 0.46255553 0.16699864 0.25938046]
  [0.87897467 0.07536439 0.53672706 0.01244488]
  [0.25477654 0.04193892 0.50363155 0.76030654]]

 [[0.38606268 0.49797986 0.54425604 0.28953229]
  [0.263271   0.08191109 0.27888038 0.02243843]
  [0.0070697  0.68134954 0.49542762 0.76839128]
  [0.27884357 0.08151369 0.47700345 0.54045055]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [838]:
minmax_array = np.random.rand(15,15) 
print("Array:\n", minmax_array)

Array:
 [[0.32452315 0.33980314 0.68532132 0.28224719 0.75929095 0.38897973
  0.47869002 0.16036418 0.96831952 0.29369226 0.33672164 0.21293265
  0.06682523 0.06106933 0.42312329]
 [0.72862417 0.40127039 0.33446978 0.91241399 0.87103183 0.31705078
  0.18866636 0.69578565 0.09711221 0.49287382 0.7422036  0.36980153
  0.67748472 0.84685917 0.12162349]
 [0.97241826 0.04404124 0.00554077 0.68636416 0.37706894 0.3796266
  0.97851296 0.427582   0.54366798 0.05615429 0.78475649 0.92209385
  0.60907813 0.42621519 0.35006586]
 [0.18703281 0.4076016  0.83377606 0.98617634 0.89596918 0.90160755
  0.91254941 0.83012849 0.97350171 0.82059691 0.01612862 0.55069507
  0.14827276 0.31193949 0.76318719]
 [0.2021144  0.64985755 0.79445424 0.7019707  0.02036064 0.42677921
  0.64585392 0.80328185 0.57783008 0.24215793 0.5337002  0.08504483
  0.27359968 0.57833415 0.75434136]
 [0.74380901 0.77205025 0.45847751 0.19650115 0.27827352 0.3715176
  0.20222413 0.10364877 0.03514758 0.85033141 0.11172903 0.4436335

In [839]:
min_val = np.min(minmax_array)
max_val = np.max(minmax_array)

print("Min Value:", min_val)
print("Max Value:", max_val)

Min Value: 0.0010904577869971233
Max Value: 0.9861763419077553


#### 9. Create a random array of size 25 and find the mean value

In [840]:
random_arr_25 = np.random.random(size=(25)) 
mean_value = np.mean(random_arr_25)

print("Array:", random_arr_25)
print("\nMean Value:", mean_value)

Array: [0.41677181 0.92866626 0.39954768 0.31138549 0.87094835 0.52654529
 0.20668723 0.33386333 0.93730729 0.5742358  0.0569986  0.4918417
 0.56960369 0.85803754 0.38656523 0.10863371 0.9994736  0.36825557
 0.04087332 0.72606936 0.65237047 0.73257342 0.11587682 0.37695043
 0.45469059]

Mean Value: 0.4977909034155851


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [841]:
array1 = np.array([2, 4, 9])
array2 = np.array([1, 14, 6])

print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [2 4 9]
Array 2: [ 1 14  6]


10.1 What is the result of *a + b*?

In [842]:
sum = array1 + array2
print(sum)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [843]:
difference = array1 - array2
print(difference)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [844]:
product = array1 * array2
print(product)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [845]:
quotient = array1 / array2
print(quotient)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [846]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) * 10
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [847]:
element_50 = matrix[1, 1]
print(element_50)

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [848]:
row_2 = matrix[1]
print(row_2)

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [849]:
col_3 = matrix[2]
print(col_3)

[70 80 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [850]:
submat = matrix[1:3, 1:3]

print(submat)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [851]:
matrix_two = np.arange(1, 13).reshape(3,4)
print(matrix_two)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [852]:
submat_two = matrix_two[1:3, 1:3]
print(submat_two)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [853]:
row_1_every_other_element = matrix_two[0, 0::2]
print(row_1_every_other_element)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [854]:
reverse_rows = matrix_two[3::-1, 3::-1]
print(reverse_rows)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


5. Write code to extract the last two columns of the matrix.

In [855]:
last_2_col = matrix_two[0::, 2::]
print(last_2_col)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [856]:
arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

print(arr1)
print(arr2)


[11  7 33]
[44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [857]:
concat_arr = np.concatenate((arr1, arr2))
print(concat_arr)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [858]:
stack_arr = np.stack((arr1, arr2))
print(stack_arr)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [859]:
arr1_new = np.array([[1, 2], [3, 4]])

arr2_new = np.array([[5, 6], [7, 8]])

5. Write code to join them horizontally (column-wise).

In [860]:
hstack_arr = np.hstack((arr1_new, arr2_new))
print(hstack_arr)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [861]:
vstack_arr = np.vstack((arr1_new, arr2_new))
print(vstack_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [862]:
arr_1D = np.arange(10, 30, 2)
arr_2D = np.random.randint(1, 50, size=(4,4))
arr_3D = np.ones((2 ,3 ,4))

print(arr_1D)
print(arr_2D)
print(arr_3D)

[10 12 14 16 18 20 22 24 26 28]
[[22 45 11 42]
 [32 14 28  7]
 [ 4 40 30 37]
 [20  4  4 17]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [863]:
arr_1D_to_2D = arr_1D.reshape(2, -1)
arr_2D_last_two_rows = arr_2D[2:4, ::]

print(arr_1D_to_2D, " \n")
print(arr_2D_last_two_rows, "\n")

arr_2D_new = arr_2D.copy()

for row in range(len(arr_2D_new)):
  for col in range(len(arr_2D_new[row])):
    if arr_2D_new[row, col] % 2 == 0:
      arr_2D_new[row, col] = -1

print("Old:\n", arr_2D)
print("\nNew: \n", arr_2D_new)

[[10 12 14 16 18]
 [20 22 24 26 28]]  

[[ 4 40 30 37]
 [20  4  4 17]] 

Old:
 [[22 45 11 42]
 [32 14 28  7]
 [ 4 40 30 37]
 [20  4  4 17]]

New: 
 [[-1 45 11 -1]
 [-1 -1 -1  7]
 [-1 -1 -1 37]
 [-1 -1 -1 17]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [864]:
print("arr_2D:\n", arr_2D)

arr_2D_mean = np.mean(arr_2D)
arr_2D_median = np.median(arr_2D)
arr_2D_std = np.std(arr_2D)
arr_2D_max = np.max(arr_2D)
arr_2D_max_idx = np.where(arr_2D == arr_2D_max)
arr_2D_sum = np.sum(arr_2D)

print("Mean: ", arr_2D_mean)
print("Median: ", arr_2D_median)
print("Standard Deviation: ", arr_2D_std)
print("Max: ", arr_2D_max, arr_2D_max_idx)
print("Sum: ",arr_2D_sum)
 


arr_2D:
 [[22 45 11 42]
 [32 14 28  7]
 [ 4 40 30 37]
 [20  4  4 17]]
Mean:  22.3125
Median:  21.0
Standard Deviation:  13.891178630699413
Max:  45 (array([0]), array([1]))
Sum:  357


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.