# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [2]:
import numpy as np

#### 2. Print the numpy version

In [35]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [42]:
arr = np.array(size=(5))
print(arr)

[]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [43]:
arr = np.array([], ndmin=(15))
arr[6] = 1
print(arr)

IndexError: index 6 is out of bounds for axis 0 with size 1

#### 5. Create a 4x4 matrix with values ranging from 0 to 11

#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

#### 7. Create a 4x4x4 array with random values

#### 8. Create a 15x15 array with random assigned values and find the min and max values

#### 9. Create a random array of size 25 and find the mean value

#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

10.1 What is the result of *a + b*?

10.2 What is the result of *a - b*?

10.3 What is the result of *a × b*?

10.4 What is the result of *a ÷ b*?

## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [8]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [13]:
matrix[2, 2]
# print(matrix[1, 1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [15]:
matrix[1]
# print(matrix[1])

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [16]:
matrix[2]
# print(matrix[2])

[70 80 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [36]:
submat = matrix[1:3, 1:3]

# print(submat)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [13]:
matrix_two = np.array([[1, 2, 3 ,4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(matrix_two)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [25]:
submat_two = matrix_two[1:3, 1:3]
print(submat_two)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [34]:
submat_three = matrix_two[1:3:2]
print(submat_three)

[[5 6 7 8]]


4. Write code to reverse the order of rows in the matrix

5. Write code to extract the last two columns of the matrix.

##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

2. Write code to join arr1 and arr2 into a single 1D array.

3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

5. Write code to join them horizontally (column-wise).

6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.