# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [261]:
import numpy as np

#### 2. Print the numpy version

In [262]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [263]:
null_array = np.full(5, None)
print(null_array)

[None None None None None]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [264]:
null_array_15 = np.full(15, None)
null_array_15[6] = 1
print(null_array_15)

[None None None None None None 1 None None None None None None None None]


#### 5. Create a 4x4 matrix with values ranging from 0 to 15

In [265]:
four_by_four_mat = np.arange(16).reshape(4, 4)
print(four_by_four_mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [266]:
arr = np.array([1, 2, 4, 0, 4, 0])
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [267]:
random_array = np.random.rand(4,4,4)
print(random_array)

[[[0.73628821 0.12264153 0.7338827  0.35422666]
  [0.46270188 0.03202393 0.44896704 0.46324985]
  [0.86284327 0.4061427  0.46979936 0.72404675]
  [0.86373339 0.59239692 0.28606085 0.02756329]]

 [[0.77140866 0.74382444 0.88698485 0.00308208]
  [0.34252587 0.08645028 0.52723962 0.9534465 ]
  [0.40719677 0.11846869 0.94362926 0.18066634]
  [0.32704666 0.98894465 0.30865461 0.13075428]]

 [[0.02299157 0.52787346 0.79572608 0.71152167]
  [0.92892049 0.03233906 0.17848545 0.45892962]
  [0.07230399 0.21767977 0.44086612 0.22845022]
  [0.31990995 0.10121625 0.14287098 0.16875615]]

 [[0.08238363 0.23296342 0.96082413 0.63173492]
  [0.69988302 0.01562731 0.40111263 0.64362596]
  [0.48127374 0.9872928  0.17597795 0.4818361 ]
  [0.22436634 0.03349395 0.10022616 0.83554843]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [268]:
minmax_array = np.random.rand(15,15) 
print("Array:\n", minmax_array)

Array:
 [[0.92043297 0.0115707  0.85718232 0.61030064 0.28744916 0.43735797
  0.98477227 0.34651241 0.84765226 0.04474718 0.20890433 0.29994414
  0.45064274 0.17986114 0.81950685]
 [0.23271246 0.54056208 0.33346359 0.49410128 0.99819759 0.75752456
  0.38362685 0.55949524 0.62078627 0.65397409 0.20734889 0.76504508
  0.76031954 0.38426949 0.44460649]
 [0.08161999 0.43980143 0.45339454 0.3288266  0.20443391 0.46136575
  0.21735731 0.41988361 0.72159177 0.24850429 0.72200715 0.62535697
  0.53907633 0.66801682 0.05967557]
 [0.6761901  0.05417864 0.24303898 0.39241773 0.46298314 0.51694957
  0.575161   0.11616164 0.15178314 0.77984791 0.5946528  0.10248708
  0.80106076 0.8897677  0.79708716]
 [0.31674604 0.39755576 0.40625864 0.95515434 0.99175728 0.06402267
  0.23683237 0.7484988  0.67247707 0.64962781 0.00363528 0.99790374
  0.57560254 0.5607523  0.47912895]
 [0.54572292 0.02205374 0.24812222 0.96506029 0.18206872 0.3161152
  0.40626595 0.31112588 0.17755131 0.55403765 0.00675246 0.464826

In [269]:
min_val = np.min(minmax_array)
max_val = np.max(minmax_array)

print("Min Value:", min_val)
print("Max Value:", max_val)

Min Value: 0.0032216276163871127
Max Value: 0.9981975884715152


#### 9. Create a random array of size 25 and find the mean value

In [270]:
random_arr_25 = np.random.random(size=(25)) 
mean_value = np.mean(random_arr_25)

print("Array:", random_arr_25)
print("\nMean Value:", mean_value)

Array: [0.91481974 0.38214459 0.40074237 0.49244792 0.95861209 0.7172819
 0.43118024 0.04174728 0.65032981 0.56776906 0.34362061 0.36380827
 0.70931448 0.15203279 0.94425255 0.06244154 0.41324113 0.97508148
 0.96128865 0.94373174 0.26724788 0.39854768 0.86750578 0.34503682
 0.18421542]

Mean Value: 0.5395376728335906


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [271]:
array1 = np.array([2, 4, 9])
array2 = np.array([1, 14, 6])

print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [2 4 9]
Array 2: [ 1 14  6]


10.1 What is the result of *a + b*?

In [272]:
sum = array1 + array2
print(sum)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [273]:
difference = array1 - array2
print(difference)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [274]:
product = array1 * array2
print(product)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [275]:
quotient = array1 / array2
print(quotient)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [276]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [277]:
element_50 = matrix[1, 1]
print(element_50)

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [278]:
row_2 = matrix[1]
print(row_2)

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [279]:
col_3 = matrix[2]
print(col_3)

[70 80 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [280]:
submat = matrix[1:3, 1:3]

print(submat)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [281]:
matrix_two = np.arange(1, 13).reshape(3,4)
print(matrix_two)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [282]:
submat_two = matrix_two[1:3, 1:3]
print(submat_two)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [283]:
row_1_every_other_element = matrix_two[0, 0::2]
print(row_1_every_other_element)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [284]:
reverse_rows = matrix_two[3::-1, 3::-1]
print(reverse_rows)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


5. Write code to extract the last two columns of the matrix.

In [285]:
last_2_col = matrix_two[0::, 2::]
print(last_2_col)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [286]:
arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

print(arr1)
print(arr2)


[11  7 33]
[44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [287]:
concat_arr = np.concatenate((arr1, arr2))
print(concat_arr)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [288]:
stack_arr = np.stack((arr1, arr2))
print(stack_arr)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [289]:
arr1_new = np.array([[1, 2], [3, 4]])

arr2_new = np.array([[5, 6], [7, 8]])

5. Write code to join them horizontally (column-wise).

In [290]:
hstack_arr = np.hstack((arr1_new, arr2_new))
print(hstack_arr)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [259]:
vstack_arr = np.vstack((arr1_new, arr2_new))
print(vstack_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [ ]:
arr_1D = np.array.arange(10, 28 ::2)

### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.