 # **Jimenez, Christian Rhyss R.** 
 # **Ofamin, Christian**

# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [36]:
import numpy as np

#### 2. Print the numpy version

In [37]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [38]:
null_array = np.full(5, None)
print(null_array)

[None None None None None]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [39]:
null_array_15 = np.full(15, None)
null_array_15[6] = 1
print(null_array_15)

[None None None None None None 1 None None None None None None None None]


#### 5. Create a 4x4 matrix with values ranging from 0 to 15

In [40]:
four_by_four_mat = np.arange(16).reshape(4, 4)
print(four_by_four_mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [41]:
arr = np.array([1, 2, 4, 0, 4, 0])
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [42]:
random_array = np.random.rand(4,4,4)
print(random_array)

[[[0.73785802 0.91820619 0.95480296 0.481413  ]
  [0.99791742 0.11471451 0.39685914 0.16195552]
  [0.04667241 0.68978104 0.1891608  0.53755207]
  [0.64158038 0.44088023 0.19707319 0.92756698]]

 [[0.27323956 0.59810155 0.7055159  0.18866174]
  [0.79339607 0.34946266 0.87830639 0.1479985 ]
  [0.41555205 0.59931485 0.267797   0.23183246]
  [0.55828669 0.75901279 0.35479408 0.18442047]]

 [[0.4180677  0.77155028 0.42575305 0.33510531]
  [0.63879071 0.45745517 0.2566078  0.53415223]
  [0.03803886 0.52200013 0.3688401  0.27423989]
  [0.0893097  0.50447043 0.39357662 0.90755684]]

 [[0.06310572 0.26366333 0.79667733 0.30347664]
  [0.3332116  0.68236837 0.21176299 0.57287542]
  [0.74262408 0.74043175 0.35912637 0.80047097]
  [0.69150595 0.79150572 0.65445546 0.81269441]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [43]:
minmax_array = np.random.rand(15,15) 
print("Array:\n", minmax_array)

Array:
 [[0.63345577 0.0599721  0.91319506 0.05340559 0.62039744 0.83183459
  0.2634748  0.88281696 0.88677856 0.94871756 0.24756503 0.84349573
  0.6699847  0.285988   0.173841  ]
 [0.68530336 0.67788312 0.37239872 0.12407393 0.95399243 0.17246294
  0.28336366 0.74579326 0.94968093 0.20923389 0.59964432 0.10145143
  0.51223381 0.17664352 0.60435383]
 [0.72460064 0.70855547 0.45115042 0.39506721 0.23431571 0.13716434
  0.31955736 0.28058208 0.86842306 0.93189578 0.2699948  0.7292143
  0.25278638 0.93346731 0.16845334]
 [0.29106119 0.89365208 0.32008891 0.49870148 0.50067579 0.81994496
  0.5204985  0.95020415 0.66798496 0.52501732 0.28376049 0.24332437
  0.88428774 0.78802513 0.24236911]
 [0.77382149 0.86602828 0.53708674 0.427575   0.85640773 0.30235982
  0.27807878 0.78038003 0.46372919 0.00494188 0.43323384 0.20615716
  0.39139164 0.44596594 0.23406463]
 [0.33524883 0.09109163 0.91189949 0.84521631 0.57844942 0.83745508
  0.13993484 0.04872388 0.73336319 0.99474712 0.30697977 0.622842

In [44]:
min_val = np.min(minmax_array)
max_val = np.max(minmax_array)

print("Min Value:", min_val)
print("Max Value:", max_val)

Min Value: 0.004231354195855186
Max Value: 0.9947471158940832


#### 9. Create a random array of size 25 and find the mean value

In [45]:
random_arr_25 = np.random.random(size=(25)) 
mean_value = np.mean(random_arr_25)

print("Array:", random_arr_25)
print("\nMean Value:", mean_value)

Array: [0.27336507 0.86454779 0.6430451  0.74199995 0.77617787 0.5748357
 0.95943312 0.28088898 0.67208918 0.26564097 0.84730974 0.38762185
 0.1451487  0.42928119 0.17777459 0.62463424 0.24466766 0.20150411
 0.77434915 0.18490105 0.35878904 0.86405268 0.37149451 0.02286359
 0.16465267]

Mean Value: 0.4740427399483589


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [46]:
array1 = np.array([2, 4, 9])
array2 = np.array([1, 14, 6])

print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [2 4 9]
Array 2: [ 1 14  6]


10.1 What is the result of *a + b*?

In [47]:
sum = array1 + array2
print(sum)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [48]:
difference = array1 - array2
print(difference)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [49]:
product = array1 * array2
print(product)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [50]:
quotient = array1 / array2
print(quotient)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [51]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) * 10
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [52]:
element_50 = matrix[1, 1]
print(element_50)

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [53]:
row_2 = matrix[1]
print(row_2)

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [54]:
col_3 = matrix[2]
print(col_3)

[70 80 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [55]:
submat = matrix[1:3, 1:3]

print(submat)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [56]:
matrix_two = np.arange(1, 13).reshape(3,4)
print(matrix_two)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [57]:
submat_two = matrix_two[1:3, 1:3]
print(submat_two)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [58]:
row_1_every_other_element = matrix_two[0, 0::2]
print(row_1_every_other_element)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [59]:
reverse_rows = matrix_two[3::-1, 3::-1]
print(reverse_rows)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


5. Write code to extract the last two columns of the matrix.

In [60]:
last_2_col = matrix_two[0::, 2::]
print(last_2_col)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [61]:
arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

print(arr1)
print(arr2)


[11  7 33]
[44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [62]:
concat_arr = np.concatenate((arr1, arr2))
print(concat_arr)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [63]:
stack_arr = np.stack((arr1, arr2))
print(stack_arr)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [64]:
arr1_new = np.array([[1, 2], [3, 4]])

arr2_new = np.array([[5, 6], [7, 8]])

5. Write code to join them horizontally (column-wise).

In [65]:
hstack_arr = np.hstack((arr1_new, arr2_new))
print(hstack_arr)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [66]:
vstack_arr = np.vstack((arr1_new, arr2_new))
print(vstack_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [67]:
arr_1D = np.arange(10, 30, 2)
arr_2D = np.random.randint(1, 50, size=(4,4))
arr_3D = np.ones((2 ,3 ,4))

print(arr_1D)
print(arr_2D)
print(arr_3D)

[10 12 14 16 18 20 22 24 26 28]
[[45 24 31  8]
 [32 43 29  9]
 [27 33 16 13]
 [21 11 35 24]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [68]:
arr_1D_to_2D = arr_1D.reshape(2, -1)
arr_2D_last_two_rows = arr_2D[2:4, ::]

print(arr_1D_to_2D, " \n")
print(arr_2D_last_two_rows, "\n")

arr_2D_new = arr_2D.copy()

for row in range(len(arr_2D_new)):
  for col in range(len(arr_2D_new[row])):
    if arr_2D_new[row, col] % 2 == 0:
      arr_2D_new[row, col] = -1

print("Old:\n", arr_2D)
print("\nNew: \n", arr_2D_new)

[[10 12 14 16 18]
 [20 22 24 26 28]]  

[[27 33 16 13]
 [21 11 35 24]] 

Old:
 [[45 24 31  8]
 [32 43 29  9]
 [27 33 16 13]
 [21 11 35 24]]

New: 
 [[45 -1 31 -1]
 [-1 43 29  9]
 [27 33 -1 13]
 [21 11 35 -1]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [69]:
print("arr_2D:\n", arr_2D)

arr_2D_mean = np.mean(arr_2D)
arr_2D_median = np.median(arr_2D)
arr_2D_std = np.std(arr_2D)
arr_2D_max = np.max(arr_2D)
arr_2D_max_idx = np.where(arr_2D == arr_2D_max)
arr_2D_sum = np.sum(arr_2D)

print("Mean: ", arr_2D_mean)
print("Median: ", arr_2D_median)
print("Standard Deviation: ", arr_2D_std)
print("Max: ", arr_2D_max, arr_2D_max_idx)
print("Sum: ",arr_2D_sum)


arr_2D:
 [[45 24 31  8]
 [32 43 29  9]
 [27 33 16 13]
 [21 11 35 24]]
Mean:  25.0625
Median:  25.5
Standard Deviation:  11.115691330277214
Max:  45 (array([0]), array([0]))
Sum:  401


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [87]:
arr_10x10 = np.random.rand(10, 10)


column_min = np.min(arr_10x10, axis=0)


flat_indices = np.argpartition(arr_10x10.flatten(), -5)[-5:]
top_5_indices = np.unravel_index(flat_indices, arr_10x10.shape)


print(arr_10x10)
print("\nMinimum values along each column:")
print(column_min)
print("\nIndices of the top 5 largest values:")
print(list(zip(top_5_indices[0], top_5_indices[1])))

[[0.68403135 0.46108212 0.99974382 0.87475339 0.62174726 0.28574875
  0.16703642 0.72936539 0.53689919 0.3277374 ]
 [0.29762123 0.07180868 0.93109364 0.05247048 0.67968701 0.81596513
  0.15072575 0.20313923 0.56480751 0.30317884]
 [0.58433731 0.83262298 0.41836402 0.79257574 0.51058616 0.78268084
  0.6040208  0.41422567 0.42097059 0.555394  ]
 [0.92768246 0.8578315  0.05570291 0.42232411 0.01656851 0.13915757
  0.07840241 0.52927451 0.10818097 0.20672259]
 [0.32680952 0.45170415 0.95084452 0.07182886 0.24790459 0.25672219
  0.48099105 0.38947753 0.35188288 0.14866806]
 [0.18412687 0.36690046 0.08500535 0.66344729 0.38600955 0.29595814
  0.92573292 0.28816824 0.43899584 0.0429944 ]
 [0.19506511 0.02895102 0.77348131 0.1329897  0.57631068 0.27636769
  0.45512325 0.64010916 0.05765691 0.03212786]
 [0.25197051 0.05525534 0.57306753 0.81119715 0.907844   0.48929681
  0.83907183 0.35327995 0.06589262 0.2515937 ]
 [0.5309871  0.94762131 0.0947849  0.09180124 0.27388782 0.69906217
  0.08850658